mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:*/mapper/*.xml
spring:
  datasource:
#    driver-class-name: org.h2.Driver
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
  sql:
    init:
#      mode: never
      schema-locations: classpath:sql/schema-mysql.sql
      data-locations: classpath:sql/data-mysql.sql


