#spring:
  # Spring Security 配置项，对应 SecurityProperties 配置类
#  security:
#    # 配置默认的 InMemoryUserDetailsManager 的用户账号与密码。
#    user:
#      name: user # 账号
#      password: 123 # 密码
#      roles: USER # 拥有角色

spring:
  # 用户认证相关数据库链接信息
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?characterEncoding=UTF-8&useSSL=false&useUnicode=true
    username: root
    password: 12345678
  mvc:
    view:
      prefix:

