#spring.h2.console.enabled=true

spring:
  # 用户认证相关数据库链接信息
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useSSL=false&useUnicode=true
    username: root
    password: 12345678